SEED: 42

OUTPUT:
  DIR: demo/output
  FILE_PREFIX: custom_demo

RULE:
  CUSTOM_CHARACTERISTICS_FUNCTION: electronics_only
  NUM_PRODUCTS: 30
  DATE_START: "2024-11-01"
  DATE_END: "2024-11-30"
  SALE_PROB: 0.6
